# ── Theme: Catppuccin Mocha ──
# https://github.com/catppuccin/catppuccin
#
# Base      #1e1e2e    Overlay0  #6c7086
# Mantle    #181825    Blue      #89b4fa
# Crust     #11111b    Sapphire  #74c7ec
# Surface0  #313244    Sky       #89dceb
# Surface1  #45475a    Teal      #94e2d5
# Surface2  #585b70    Green     #a6e3a1
# Text      #cdd6f4    Yellow    #f9e2af
# Subtext1  #bac2de    Peach     #fab387
# Subtext0  #a6adc8    Red       #f38ba8
# Lavender  #b4befe    Mauve     #cba6f7

# class                 border  bg      text    indicator child_border
client.focused          #89b4fa #1e1e2e #cdd6f4 #89dceb   #89b4fa
client.focused_inactive #45475a #1e1e2e #6c7086 #45475a   #45475a
client.unfocused        #313244 #1e1e2e #6c7086 #313244   #313244
client.urgent           #f38ba8 #1e1e2e #cdd6f4 #f38ba8   #f38ba8
