source $HOME/.config/vim/general/settings.vim
source $HOME/.config/vim/vim-plug/plugins.vim
source $HOME/.config/vim/keys/mappings.vim
source $HOME/.config/vim/keys/which-key.vim
source $HOME/.config/vim/plug-config/coc-config.vim
source $HOME/.config/vim/plug-config/syntastic.vim
source $HOME/.config/vim/plug-config/ranger.vim
source $HOME/.config/vim/plug-config/fzf.vim
