includes = [".dotter/brainiac-conf.toml"]

packages = [
	"alacritty",
	"bat",
	"environment",
	"i3",
	"sway",
	"swayidle",
	"swaylock",
	"dunst",
	"environment",
	"eww",
	"helix",
	"hypr",
	"nvim",
	"picom",
	"rofi",
	"starship",
	"tmux",
	"waybar",
	"wezterm",
	"wpaperd",
	"zsh",
	"zellij",
]
