includes = [".dotter/thinkpad.toml"]
packages = [
  "alacritty",
	"bat",
	"dunst",
  "environment",
  "helix",
	"hypr",
  "nvim",
	"rofi",
  "starship",
	"swayidle",
	"swaylock",
	"wpaperd",
	"waybar",
  "zsh",
  "zellij"
]
