# Reference : https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#setup

[bat.files]
bat="~/.config/bat"

[alacritty.files]
alacritty="~/.config/alacritty"

[nvim.files]
nvim={ target = "~/.config/nvim", type = "symbolic" }

[starship.files]
starship="~/.config/starship"

[zsh.files]
"zsh/zshenv"="~/.zshenv"
"zsh/zshrc"="~/.config/zsh/.zshrc"

[helix.files]
helix="~/.config/helix"

[environment.files]
environment="~/.config/environment.d"

[zellij.files]
"zellij/config.kdl"="~/.config/zellij/config.kdl"
"zellij/plugins/zellij-autolock.wasm"={ target = "~/.config/zellij/plugins/zellij-autolock.wasm", type = "symbolic"}

[git.files]
"git/config"="~/.gitconfig"
