# Reference : https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#setup

[alacritty.files]
alacritty="~/.config/alacritty"

[i3.files]
"i3/config"="~/.config/i3/config"
i3_sway="~/.config/i3_sway"
# "i3/config.d"="~/.config/i3/config.d"

[sway.files]
"sway/config"="~/.config/sway/config"

[swayidle.files]
"swayidle"="~/.config/swayidle"

[swaylock.files]
"swaylock"="~/.config/swaylock"


[dunst.files]
dunst="~/.config/dunst"

# [lf.files]
# lf= { target = "~/.config/lf", type = "symbolic" }

[nvim.files]
nvim={ target = "~/.config/nvim", type = "symbolic" }

[picom.files]
picom="~/.config/picom"

[rofi.files]
rofi="~/.config/rofi"

[starship.files]
starship="~/.config/starship"

[tmux.files]
tmux="~/.config/tmux"

[wezterm.files]
wezterm="~/.config/wezterm"

[zsh.files]
"zsh/zshenv"="~/.zshenv"
"zsh/zshrc"="~/.config/zsh/.zshrc"

[hypr.files]
"hypr/hyprland.conf"="~/.config/hypr/hyprland.conf"

[eww.files]
eww="~/.config/eww"

[waybar.files]
waybar="~/.config/waybar"

[wpaperd.files]
wpaperd="~/.config/wpaperd"

[helix.files]
helix="~/.config/helix"

[environment.files]
environment="~/.config/environment.d"

[zellij.files]
zellij="~/.config/zellij"
