includes = [".dotter/urithiru-conf.toml"]

packages = [
	"alacritty",
	"bat",
	"environment",
	"git",
	"swayidle",
	"swaylock",
	"helix",
	"hypr",
	"nvim",
	"rofi",
	"starship",
	"tmux",
	"waybar",
	"wpaperd",
	"zsh",
	"zellij",
]
