HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY

export LANG=en_US.utf-8
export LC_ALL=en_US.utf-8

# Download Znap, if it's not there yet.
[[ -f ~/.local/git/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/.local/git/zsh-snap

source ~/.local/git/zsh-snap/znap.zsh  # Start Znap
# if [ -n "$DESKTOP_SESSION" ];then
#     export SSH_AUTH_SOCK
# fi

if [ -f /usr/share/fzf/completion.zsh ];then
	source /usr/share/fzf/completion.zsh
fi

if [ -f /usr/share/fzf/key-bindings.zsh ];then
	source /usr/share/fzf/key-bindings.zsh
fi

znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source chisui/zsh-nix-shell
znap source nix-community/nix-zsh-completions
# znap source casonadams/skim.zsh
znap source lincheney/fzf-tab-completion zsh

#atuin
znap source atuinsh/atuin

#Source nvm
if [ -f /usr/share/nvm/init-nvm.sh ]; then
	source /usr/share/nvm/init-nvm.sh
fi

alias vim=nvim
# alias hx=helix

# ls
TREE_IGNORE="cache|log|logs|node_modules|vendor"

alias ls=' eza --group-directories-first'
alias la=' ls -a'
alias ll=' ls --git -l'
alias lt=' ls --tree -D -L 2 -I ${TREE_IGNORE}'
alias ltt=' ls --tree -D -L 3 -I ${TREE_IGNORE}'
alias lttt=' ls --tree -D -L 4 -I ${TREE_IGNORE}'
alias ltttt=' ls --tree -D -L 5 -I ${TREE_IGNORE}'

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Edit line in vim buffer ctrl-v
autoload edit-command-line; zle -N edit-command-line
bindkey '^v' edit-command-line
# Enter vim buffer from normal mode
autoload -U edit-command-line && zle -N edit-command-line && bindkey -M vicmd "^v" edit-command-line
# Use vim keys in tab complete menu:
zstyle ':completion:*' menu select
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'left' vi-backward-char
bindkey -M menuselect 'down' vi-down-line-or-history
bindkey -M menuselect 'up' vi-up-line-or-history
bindkey -M menuselect 'right' vi-forward-char
# Fix backspace bug when switching modes
bindkey "^?" backward-delete-char

#Completions are not case sensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# fzf compiletions also search in display string
zstyle ':completion:*' fzf-search-display true
#
# Enable this to make the completions case insensitive only when no case sensitive matches are found
# zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
eval "$(starship init zsh)"
# export ZELLIJ_AUTO_EXIT=true
# eval "$(zellij setup --generate-auto-start zsh)"

if [ -f /etc/profile.d/conda.sh ]; then
  source /etc/profile.d/conda.sh
fi
# Conda/Mamba environment
if [ -f /usr/bin/micromamba ]; then
  eval "$(/usr/bin/micromamba shell hook --shell zsh)"
fi

if command -v zoxide > /dev/null; then
  eval "$(zoxide init zsh)"
fi

load-env() {
	if [[ ! -f .env ]]; then
		return
	fi
	set -a && source .env && set +a
}

add-zsh-hook chpwd load-env

. "$HOME/.local/share/../bin/env"
