[preferred]
default=gnome;gtk;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
# org.freedesktop.impl.portal.Secret=kde;
# Requires xdg-desktop-portal-kde to be installed
# org.freedesktop.impl.portal.ScreenCast=kde;
# org.freedesktop.impl.portal.RemoteDesktop=kde;
